name: "Deploy Maven Package"
description: "Deploys Maven Package"
inputs:
  java-version:
    default: 17
    description: "Version of Java to build with"
  java-distribution:
    default: "temurin"
    description: "Distribution of Java to use"
runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4.2.1
      with:
        java-version: ${{ inputs.java-version }}
        distribution: temurin

    - name: Set environment variables
      run: |
        echo "STR_USERNAME=${{ github.actor }}" >> $GITHUB_ENV
        echo "STR_PASSWORD=${{ github.token }}" >> $GITHUB_ENV
      shell: bash

    - name: Configure Maven settings
      run: |
        mkdir -p $HOME/.m2
        echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd\"><servers><server><id>github</id><username>${STR_USERNAME}</username><password>${STR_PASSWORD}</password></server></servers></settings>" > $HOME/.m2/settings.xml
      shell: bash

    - name: Deploy with Maven
      run: mvn deploy
      shell: bash
